CREATE or REPLACE TRIGGER set_nls_onlogon
AFTER LOGON ON DATABASE
BEGIN
   if (user in ('OPENPTK')) then
      EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_SORT=BINARY_CI';
      EXECUTE IMMEDIATE 'ALTER SESSION SET NLS_COMP=LINGUISTIC';
   end if;
END set_nlslogon;
/
