CREATE TABLE MEDIA 
(
  UUID VARCHAR2(256) NOT NULL 
, NAME VARCHAR2(256) 
, TYPE VARCHAR2(64) 
, FILESIZE INT 
, MODIFIED VARCHAR2(64) 
, CONTEXT VARCHAR2(256) 
, SUBJECT VARCHAR2(256) 
, RELATIONSHIP VARCHAR2(256) 
, DIGEST VARCHAR2(256) 
, DATA BLOB 
, CONSTRAINT MEDIA_PK PRIMARY KEY 
  (
    UUID 
  )
  ENABLE 
);

CREATE TABLE LOCATIONS 
(
  ID VARCHAR2(32) NOT NULL 
, DESCRIPTION VARCHAR2(32) NOT NULL 
, STREET VARCHAR2(64) 
, CITY VARCHAR2(48) 
, STATE VARCHAR2(8) 
, POSTALCODE VARCHAR2(12) 
);

CREATE TABLE EMPLOYEES 
(
  ID VARCHAR2(64) NOT NULL 
, FNAME VARCHAR2(64) NOT NULL 
, LNAME VARCHAR2(64) NOT NULL 
, FULLNAME VARCHAR2(64) 
, EMAIL VARCHAR2(64) 
, TITLE VARCHAR2(32) 
, TELEPHONE VARCHAR2(32) 
, MANAGER VARCHAR2(32) 
, ROLES VARCHAR2(32) 
, ORG VARCHAR2(32) 
, LOCATION VARCHAR2(32) 
, PASSWORD VARCHAR2(32) 
, FORGOTDATA VARCHAR2(256) 
, PHOTO BLOB 
, CONSTRAINT EMPLOYEES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE INDEX MEDIA_CONTEXT ON MEDIA (CONTEXT);

CREATE INDEX MEDIA_SUBJECT ON MEDIA (SUBJECT);

CREATE INDEX MEDIA_RELATIONSHIP ON MEDIA (RELATIONSHIP);

CREATE INDEX EMPLOYEES_FNAME ON EMPLOYEES (nlssort(FNAME,'NLS_SORT=BINARY_CI'));

CREATE INDEX EMPLOYEES_LNAME ON EMPLOYEES (nlssort(LNAME,'NLS_SORT=BINARY_CI'));

CREATE INDEX EMPLOYEES_MANAGER ON EMPLOYEES (nlssort(MANAGER,'NLS_SORT=BINARY_CI'));
